ProyectoAgendaCultural/ProyectoAgendaCultural/Controllers/EventoOrganizadorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoAgendaCultural.Models;

namespace ProyectoAgendaCultural.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class EventoOrganizadorController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: EventoOrganizador
        public ActionResult Index()
        {
            var eventoOrganizadorDb = db.EventoOrganizadorDb.Include(e => e.Evento).Include(e => e.Organizador);
            return View(eventoOrganizadorDb.ToList());
        }

        // GET: EventoOrganizador/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventoOrganizador eventoOrganizador = db.EventoOrganizadorDb.Find(id);
            if (eventoOrganizador == null)
            {
                return HttpNotFound();
            }
            return View(eventoOrganizador);
        }

        // GET: EventoOrganizador/Create
        public ActionResult Create()
        {
            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre");
            ViewBag.OrganizadorId = new SelectList(db.OrganizadorDb, "Id", "Nombre");
            return View();
        }

        // POST: EventoOrganizador/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,EventoId,OrganizadorId")] EventoOrganizador eventoOrganizador)
        {
            if (ModelState.IsValid)
            {
                db.EventoOrganizadorDb.Add(eventoOrganizador);
                db.SaveChanges();
                return RedirectToAction("Create","Presentacion");
            }

            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre", eventoOrganizador.EventoId);
            ViewBag.OrganizadorId = new SelectList(db.OrganizadorDb, "Id", "Nombre", eventoOrganizador.OrganizadorId);
            return View(eventoOrganizador);
        }

        //CREAR NUEVO REGISTRO
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearNuevo([Bind(Include = "Id,EventoId,OrganizadorId")] EventoOrganizador eventoOrganizador)
        {
            if (ModelState.IsValid)
            {
                db.EventoOrganizadorDb.Add(eventoOrganizador);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre", eventoOrganizador.EventoId);
            ViewBag.OrganizadorId = new SelectList(db.OrganizadorDb, "Id", "Nombre", eventoOrganizador.OrganizadorId);
            return View("Create");
        }

        // GET: EventoOrganizador/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventoOrganizador eventoOrganizador = db.EventoOrganizadorDb.Find(id);
            if (eventoOrganizador == null)
            {
                return HttpNotFound();
            }
            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre", eventoOrganizador.EventoId);
            ViewBag.OrganizadorId = new SelectList(db.OrganizadorDb, "Id", "Nombre", eventoOrganizador.OrganizadorId);
            return View(eventoOrganizador);
        }

        // POST: EventoOrganizador/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,EventoId,OrganizadorId")] EventoOrganizador eventoOrganizador)
        {
            if (ModelState.IsValid)
            {
                db.Entry(eventoOrganizador).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre", eventoOrganizador.EventoId);
            ViewBag.OrganizadorId = new SelectList(db.OrganizadorDb, "Id", "Nombre", eventoOrganizador.OrganizadorId);
            return View(eventoOrganizador);
        }

        // GET: EventoOrganizador/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            EventoOrganizador eventoOrganizador = db.EventoOrganizadorDb.Find(id);
            if (eventoOrganizador == null)
            {
                return HttpNotFound();
            }
            return View(eventoOrganizador);
        }

        // POST: EventoOrganizador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            EventoOrganizador eventoOrganizador = db.EventoOrganizadorDb.Find(id);
            db.EventoOrganizadorDb.Remove(eventoOrganizador);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/EventoOrganizador/Create.cshtml
@model ProyectoAgendaCultural.Models.EventoOrganizador

@{
    ViewBag.Title = "Create";
}

<link href="~/Content/estilo_menuVertical.css" rel="stylesheet" />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--Menu de administrador-->
            @{Html.RenderPartial("_menuVertical");}
            <hr class="hidden-sm hidden-md hidden-lg">
        </div>
        <div class="col-sm-9">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h2 style="color:black">Publicar evento (Organizadores)</h2>
                </div>
                <div class="panel-body">

                    <form id="form1" method="post">
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="col-md-10">
                                <h4><b>Información del organizador del evento</b></h4>
                                <h5>Los campos marcados con (*) son obligatorios</h5>
                                <hr />
                            </div>
                            <br />
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="clearfix" style="background-color: #00b5e4">
                                        <h5 style="margin-left:10px"><b>EVENTO</b></h5>
                                    </div>
                                    <br />
                                </div>
                                <div class="col-md-10">
                                    <p style="font-weight:bold">Seleccione el evento o cree uno nuevo</p>
                                    @Html.DropDownList("EventoId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.EventoId, "", new { @class = "text-danger" })
                                    <br />
                                    <a class="btn btn-default" href="/Evento/Create" style="background-color: #00b5e4"><b>Agregar evento</b></a>
                                    <br />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="clearfix" style="background-color: #00b5e4">
                                        <h5 style="margin-left:10px"><b>ORGANIZADOR</b></h5>
                                    </div>
                                    <br />
                                </div>
                                <div class="col-md-10">
                                    <p style="font-weight:bold">Seleccione la entidad organizadora o cree una nueva</p>
                                    @Html.DropDownList("OrganizadorId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.OrganizadorId, "", new { @class = "text-danger" })
                                    <br />
                                    <a class="btn btn-default" href="/Organizador/Create" style="background-color: #00b5e4"><b>Agregar organizador</b></a>
                                    <br />
                                    <hr />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <input type="submit" value="Guardar y asignar nuevo organizador" class="btn btn-default" id="guardarNuevo" />
                                    <input type="submit" value="Guardar y continuar" class="btn btn-success" id="guardar"/>
                                    <a href="/Presentacion/Create" s class="btn btn-default">Continuar sin guardar</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
      $("#guardar").click(function() {
          var form = $("form#form1");
          form.attr("action", "@Url.Action("Create","EventoOrganizador")");
          form.submit();

          //alert("Registro guardado correctamente");
      });

      $("#guardarNuevo").click(function() {
          var form = $("form#form1");
          form.attr("action", "@Url.Action("CrearNuevo", "EventoOrganizador")");
          form.submit();
          //alert("Registro guardado correctamente");
      });
</script>

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/EventoOrganizador/Delete.cshtml
@model ProyectoAgendaCultural.Models.EventoOrganizador

@{
    ViewBag.Title = "Delete";
}
<link href="~/Content/estilo_menuVertical.css" rel="stylesheet" />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--Menu de administrador-->
            @{Html.RenderPartial("_menuVertical");}
            <hr class="hidden-sm hidden-md hidden-lg">
        </div>
        <div class="col-sm-9">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 style="color:black">Eliminar organizador de evento</h2>
                </div>
                <div class="panel-body">
                    <h3>Esta seguro de borrar este registro?</h3>
                    <div>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Evento.Nombre)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Evento.Nombre)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Organizador.Nombre)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Organizador.Nombre)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="col-md-offset-3 col-md-9">
                                <input type="submit" value="Borrar" class="btn btn-danger" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        }
                    </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/EventoOrganizador/Details.cshtml
@model ProyectoAgendaCultural.Models.EventoOrganizador

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>EventoOrganizador</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Evento.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Evento.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Organizador.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Organizador.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/EventoOrganizador/Edit.cshtml
@model ProyectoAgendaCultural.Models.EventoOrganizador

@{
    ViewBag.Title = "Edit";
}

<link href="~/Content/estilo_menuVertical.css" rel="stylesheet" />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--Menu de administrador-->
            @{Html.RenderPartial("_menuVertical");}
            <hr class="hidden-sm hidden-md hidden-lg">
        </div>
        <div class="col-sm-9">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h2 style="color:black">Editar organizadores de evento</h2>
                </div>
                <div class="panel-body">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="col-md-10">
                                <h4><b>Editar información del organizador del evento</b></h4>
                                <h5>Los campos marcados con (*) son obligatorios</h5>
                                <hr />
                            </div>
                            <br />
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="clearfix" style="background-color: #00b5e4">
                                        <h5 style="margin-left:10px"><b>EVENTO</b></h5>
                                    </div>
                                    <br />
                                </div>
                                <div class="col-md-10">
                                    <p style="font-weight:bold">Seleccione el evento o cree uno nuevo</p>
                                    @Html.DropDownList("EventoId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.EventoId, "", new { @class = "text-danger" })
                                    <br />
                                    <a class="btn btn-default" href="/Evento/Create" style="background-color: #00b5e4"><b>Agregar evento</b></a>
                                    <br />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="clearfix" style="background-color: #00b5e4">
                                        <h5 style="margin-left:10px"><b>ORGANIZADOR</b></h5>
                                    </div>
                                    <br />
                                </div>
                                <div class="col-md-10">
                                    <p style="font-weight:bold">Seleccione la entidad organizadora o cree una nueva</p>
                                    @Html.DropDownList("OrganizadorId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.OrganizadorId, "", new { @class = "text-danger" })
                                    <br />
                                    <a class="btn btn-default" href="/Organizador/Create" style="background-color: #00b5e4"><b>Agregar organizador</b></a>
                                    <br />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-3 col-md-9">
                                    <input type="submit" value="Guardar cambios" class="btn btn-success" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>


<div>
    @Html.ActionLink("Inicio", "Index")
</div>

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/EventoOrganizador/Index.cshtml
@model IEnumerable<ProyectoAgendaCultural.Models.EventoOrganizador>

@{
    ViewBag.Title = "Index";
}

<link href="~/Content/estilo_menuVertical.css" rel="stylesheet" />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--Menu de administrador-->
            @{Html.RenderPartial("_menuVertical");}
            <hr class="hidden-sm hidden-md hidden-lg">
        </div>
        <div class="col-sm-9">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h2 style="color:black">Listado de organizadores por evento</h2>
                </div>
                <div class="panel-body">
                    <p>
                        @Html.ActionLink("Crear nuevo registro", "Create")
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Evento.Nombre)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Organizador.Nombre)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Evento.Nombre)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Organizador.Nombre)
                                </td>
                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Borrar", "Delete", new { id = item.Id })
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>