ProyectoAgendaCultural/ProyectoAgendaCultural/Controllers/PresentacionController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoAgendaCultural.Models;

namespace ProyectoAgendaCultural.Controllers
{
    [Authorize(Roles = "Administrador")]
    public class PresentacionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Presentacion
        public ActionResult Index()
        {
            var presentacionDb = db.PresentacionDb.Include(p => p.Artista).Include(p => p.Evento);
            return View(presentacionDb.ToList());
        }

        // GET: Presentacion/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Presentacion presentacion = db.PresentacionDb.Find(id);
            if (presentacion == null)
            {
                return HttpNotFound();
            }
            return View(presentacion);
        }

        // GET: Presentacion/Create
        public ActionResult Create()
        {
            ViewBag.ArtistaId = new SelectList(db.ArtistaDb, "Id", "NombreCompleto");
            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre");
            return View();
        }

        // POST: Presentacion/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,ArtistaId,EventoId")] Presentacion presentacion)
        {
            if (ModelState.IsValid)
            {
                db.PresentacionDb.Add(presentacion);
                db.SaveChanges();
                return RedirectToAction("Publicar_evento","Administrador");
            }

            ViewBag.ArtistaId = new SelectList(db.ArtistaDb, "Id", "Cedula", presentacion.ArtistaId);
            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre", presentacion.EventoId);
            return View(presentacion);
        }

        //CREAR NUEVO REGISTRO
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CrearNuevo([Bind(Include = "Id,ArtistaId,EventoId")] Presentacion presentacion)
        {
            if (ModelState.IsValid)
            {
                db.PresentacionDb.Add(presentacion);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            ViewBag.ArtistaId = new SelectList(db.ArtistaDb, "Id", "Cedula", presentacion.ArtistaId);
            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre", presentacion.EventoId);
            return View("Create");
        }

        // GET: Presentacion/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Presentacion presentacion = db.PresentacionDb.Find(id);
            if (presentacion == null)
            {
                return HttpNotFound();
            }
            ViewBag.ArtistaId = new SelectList(db.ArtistaDb, "Id", "NombreCompleto", presentacion.ArtistaId);
            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre", presentacion.EventoId);
            return View(presentacion);
        }

        // POST: Presentacion/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,ArtistaId,EventoId")] Presentacion presentacion)
        {
            if (ModelState.IsValid)
            {
                db.Entry(presentacion).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ArtistaId = new SelectList(db.ArtistaDb, "Id", "Cedula", presentacion.ArtistaId);
            ViewBag.EventoId = new SelectList(db.EventoDb, "Id", "Nombre", presentacion.EventoId);
            return View(presentacion);
        }

        // GET: Presentacion/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Presentacion presentacion = db.PresentacionDb.Find(id);
            if (presentacion == null)
            {
                return HttpNotFound();
            }
            return View(presentacion);
        }

        // POST: Presentacion/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Presentacion presentacion = db.PresentacionDb.Find(id);
            db.PresentacionDb.Remove(presentacion);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/Presentacion/Create.cshtml
@model ProyectoAgendaCultural.Models.Presentacion

@{
    ViewBag.Title = "Create";
}

<link href="~/Content/estilo_menuVertical.css" rel="stylesheet" />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--Menu de administrador-->
            @{Html.RenderPartial("_menuVertical");}
            <hr class="hidden-sm hidden-md hidden-lg">
        </div>
        <div class="col-sm-9">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h2 style="color:black">Publicar evento (Artistas)</h2>
                </div>
                <div class="panel-body">

                    <form id="form1" method="post">
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="col-md-10">
                                <h4><b>Información de los artistas participantes del evento</b></h4>
                                <h5>Los campos marcados con (*) son obligatorios</h5>
                                <hr />
                            </div>
                            <br />
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="clearfix" style="background-color: #00b5e4">
                                        <h5 style="margin-left:10px"><b>ARTISTA</b></h5>
                                    </div>
                                    <br />
                                </div>
                                <div class="col-md-10">
                                    <p style="font-weight:bold">Seleccione un artista o cree un perfil de artista</p>
                                    @Html.DropDownList("ArtistaId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ArtistaId, "", new { @class = "text-danger" })
                                    <br />
                                    <a class="btn btn-default" href="/Artista/Create" style="background-color: #00b5e4"><b>Crear perfil de artista</b></a>
                                    <br />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="clearfix" style="background-color: #00b5e4">
                                        <h5 style="margin-left:10px"><b>EVENTO</b></h5>
                                    </div>
                                    <br />
                                </div>
                                <div class="col-md-10">
                                    <p style="font-weight:bold">Seleccione el evento o cree uno nuevo</p>
                                    @Html.DropDownList("EventoId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.EventoId, "", new { @class = "text-danger" })
                                    <br />
                                    <a class="btn btn-default" href="/Evento/Create" style="background-color: #00b5e4"><b>Agregar evento</b></a>
                                    <br />
                                    <hr />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" value="Guardar y asignar nuevo artista" class="btn btn-default" id="guardarNuevo" />
                                    <input type="submit" value="Guardar y finalizar" class="btn btn-success" id="guardar" />
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
      $("#guardar").click(function() {
          var form = $("form#form1");
          form.attr("action", "@Url.Action("Create","Presentacion")");
          form.submit();

          //alert("Registro guardado correctamente");
      });

      $("#guardarNuevo").click(function() {
          var form = $("form#form1");
          form.attr("action", "@Url.Action("CrearNuevo", "Presentacion")");
          form.submit();
          //alert("Registro guardado correctamente");
      });
</script>
<a href="" class="btn btn-default"></a>

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/Presentacion/Delete.cshtml
@model ProyectoAgendaCultural.Models.Presentacion

@{
    ViewBag.Title = "Delete";
}

<link href="~/Content/estilo_menuVertical.css" rel="stylesheet" />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--Menu de administrador-->
            @{Html.RenderPartial("_menuVertical");}
            <hr class="hidden-sm hidden-md hidden-lg">
        </div>
        <div class="col-sm-9">
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 style="color:black">Eliminar artistas de evento</h2>
                </div>
                <div class="panel-body">
                    <h3>Esta seguro de borrar este registro?</h3>
                    <div>
                        <hr />
                        <dl class="dl-horizontal">
                            <dt>
                                @Html.DisplayNameFor(model => model.Artista.Cedula)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Artista.Cedula)
                            </dd>

                            <dt>
                                @Html.DisplayNameFor(model => model.Evento.Nombre)
                            </dt>

                            <dd>
                                @Html.DisplayFor(model => model.Evento.Nombre)
                            </dd>

                        </dl>

                        @using (Html.BeginForm())
                        {
                            @Html.AntiForgeryToken()

                            <div class="col-md-offset-3 col-md-9">
                                <input type="submit" value="Borrar" class="btn btn-danger" /> |
                                @Html.ActionLink("Back to List", "Index")
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/Presentacion/Details.cshtml
@model ProyectoAgendaCultural.Models.Presentacion

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Presentacion</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Artista.Cedula)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Artista.Cedula)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Evento.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Evento.Nombre)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/Presentacion/Edit.cshtml
@model ProyectoAgendaCultural.Models.Presentacion

@{
    ViewBag.Title = "Edit";
}

<link href="~/Content/estilo_menuVertical.css" rel="stylesheet" />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--Menu de administrador-->
            @{Html.RenderPartial("_menuVertical");}
            <hr class="hidden-sm hidden-md hidden-lg">
        </div>
        <div class="col-sm-9">
            <div class="panel panel-warning">
                <div class="panel-heading">
                    <h2 style="color:black">Editar artistas de evento</h2>
                </div>
                <div class="panel-body">

                    @using (Html.BeginForm())
                    {
                        @Html.AntiForgeryToken()

                        <div class="form-horizontal">
                            <h4>Presentacion</h4>
                            <hr />
                            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                            <div class="col-md-10">
                                <h4><b>Editar información de los artistas participantes del evento</b></h4>
                                <h5>Los campos marcados con (*) son obligatorios</h5>
                                <hr />
                            </div>
                            <br />
                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="clearfix" style="background-color: #00b5e4">
                                        <h5 style="margin-left:10px"><b>ARTISTA</b></h5>
                                    </div>
                                    <br />
                                </div>
                                <div class="col-md-10">
                                    <p style="font-weight:bold">Seleccione un artista o cree un perfil de artista</p>
                                    @Html.DropDownList("ArtistaId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ArtistaId, "", new { @class = "text-danger" })
                                    <br />
                                    <a class="btn btn-default" href="/Artista/Create" style="background-color: #00b5e4"><b>Crear perfil de artista</b></a>
                                    <br />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-10">
                                    <div class="clearfix" style="background-color: #00b5e4">
                                        <h5 style="margin-left:10px"><b>EVENTO</b></h5>
                                    </div>
                                    <br />
                                </div>
                                <div class="col-md-10">
                                    <p style="font-weight:bold">Seleccione el evento o cree uno nuevo</p>
                                    @Html.DropDownList("EventoId", null, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.EventoId, "", new { @class = "text-danger" })
                                    <br />
                                    <a class="btn btn-default" href="/Evento/Create" style="background-color: #00b5e4"><b>Agregar evento</b></a>
                                    <br />
                                </div>
                            </div>

                            <div class="form-group">
                                <div class="col-md-offset-3 col-md-9">
                                    <input type="submit" value="Guardar cambios" class="btn btn-success" />
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
</div>
<div>
    @Html.ActionLink("Inicio", "Index")
</div>

ProyectoAgendaCultural/ProyectoAgendaCultural/Views/Presentacion/Index.cshtml
@model IEnumerable<ProyectoAgendaCultural.Models.Presentacion>

@{
    ViewBag.Title = "Index";
}
<link href="~/Content/estilo_menuVertical.css" rel="stylesheet" />
<br />
<br />
<br />
<br />
<div class="container">
    <div class="row">
        <div class="col-sm-3">
            <!--Menu de administrador-->
            @{Html.RenderPartial("_menuVertical");}
            <hr class="hidden-sm hidden-md hidden-lg">
        </div>
        <div class="col-sm-9">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h2 style="color:black">Listado de presentaciones</h2>
                </div>
                <div class="panel-body">
                    <p>
                        @Html.ActionLink("Crear nueva presentación", "Create")
                    </p>
                    <table class="table">
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Artista.Cedula)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Evento.Nombre)
                            </th>
                            <th></th>
                        </tr>

                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Artista.NombreCompleto)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Evento.Nombre)
                                </td>
                                <td>
                                    @Html.ActionLink("Editar", "Edit", new { id = item.Id }) |
                                    @Html.ActionLink("Borrar", "Delete", new { id = item.Id })
                                </td>
                            </tr>
                        }

                    </table>
                </div>
            </div>
        </div>
    </div>
</div>